### PR TITLE
docs: add author Crispus Nzano

### PR DESCRIPTION
**Pull request by Crisnzano**

### CODE REVIEW

**Comment by Kigen29** [comment]
Approved

**Review by Kigen29 — APPROVED** [review]

**Review by nat254 — APPROVED** [review]
approved

**Review by nat254 — CHANGES_REQUESTED** [review]
please change the position of your name

**Review by nat254 — APPROVED** [review]
seen

**Review by AbigaelKirwa — APPROVED** [review]

**Review by VirginiaWanjiru — APPROVED** [review]

**Review by AbigaelKirwa — CHANGES_REQUESTED** [review]
change number to 4

**Review by nat254 — APPROVED** [review]
seen

**Review by AbigaelKirwa — APPROVED** [review]

**Review by Kigen29 — APPROVED** [review]

**Pull request merged**
