### PR TITLE
docs : add Landing Page to ReadMe File 

### PR DESCRIPTION
**Pull request by VirginiaWanjiru**

### CODE REVIEW

**Review by AbigaelKirwa — APPROVED** [review]

**Review by Kigen29 — CHANGES_REQUESTED** [review]
use docs: add landing page instead of add

**Review by Crisnzano — APPROVED** [review]
Accepted

**Review by Crisnzano — APPROVED** [review]
Approved

**Review by nat254 — APPROVED** [review]
Approved.

**Review by nat254 — APPROVED** [review]

**Review by Kigen29 — APPROVED** [review]

**Pull request merged**
